# Form implementation generated from reading ui file 'form_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 309)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.eventList = QtWidgets.QListView(parent=self.centralwidget)
        self.eventList.setGeometry(QtCore.QRect(60, 50, 281, 211))
        self.eventList.setObjectName("eventList")
        self.dateEdit = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(360, 50, 194, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.enterButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enterButton.setGeometry(QtCore.QRect(410, 110, 75, 24))
        self.enterButton.setObjectName("enterButton")
        self.eventNameLabel = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.eventNameLabel.setGeometry(QtCore.QRect(360, 80, 191, 21))
        self.eventNameLabel.setObjectName("eventNameLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enterButton.setText(_translate("MainWindow", "Добавить"))
