# Form implementation generated from reading ui file 'form_3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 479)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(470, 90, 161, 21))
        self.name_edit.setObjectName("name_edit")
        self.phone_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.phone_edit.setGeometry(QtCore.QRect(470, 120, 161, 21))
        self.phone_edit.setObjectName("phone_edit")
        self.add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(470, 150, 161, 31))
        self.add_button.setObjectName("add_button")
        self.contact_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.contact_list.setGeometry(QtCore.QRect(70, 90, 381, 271))
        self.contact_list.setObjectName("contact_list")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(470, 320, 151, 41))
        self.clear_button.setObjectName("clear_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_edit.setPlaceholderText(_translate("MainWindow", "Введите имя контакта"))
        self.phone_edit.setPlaceholderText(_translate("MainWindow", "Введите номер"))
        self.add_button.setText(_translate("MainWindow", "Добавить контакт"))
        self.clear_button.setText(_translate("MainWindow", "Очистить "))
